import "./index.css";

import { Providers } from "./GlobalRedux/provider";
import Navigation from "./components/Navigation/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navigation />
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
//<Providers>{children}</Providers>
